"""
Django settings for fescvotaciones project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vv^8wozzv%w%mm15+e15@ddvkbn#y$33xe)s!@_!9y5+@gmcsx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'votaciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fescvotaciones.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fescvotaciones.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "FESC Votaciones Admin",
    "site_header": "FESC Votaciones",
    "site_brand": None,  # Cambiar de "Administración FESC Votaciones" a None
    "site_logo": 'admin/logo.png',
    "login_logo": 'admin/logo.png',
    # "favicon": 'admin/favicon.png',  # Comentado para usar favicon simple
    "login_logo_dark": None,
    "site_logo_classes": "i",
    "site_icon": "fas fa-vote-yea",
    "welcome_sign": "Bienvenido al panel de administración FESC Votaciones",
    "copyright": "FESC - Fundación de Estudios Superiores Comfanorte",
    "search_model": ["auth.User", "votaciones.Candidato", "votaciones.Plancha", "votaciones.Votante"],
    "user_avatar": None,
    
    # Tema de colores principal
    "dark_mode_theme": None,
    
    # CSS personalizado con los colores del degradado
    "custom_css": "admin/css/custom_admin.css",
    "custom_js": None,
    
    # Enlaces del menú superior
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:dashboard", "permissions": ["auth.view_user"], "icon": "fas fa-chart-bar"},
        {"name": "Ver Sitio", "url": "/", "new_window": True},
        {"app": "votaciones"}
    ],
    
    # Enlaces del menú de usuario
    "usermenu_links": [
        {"name": "Ver Sitio Web", "url": "/", "new_window": True, "icon": "fas fa-external-link-alt"},
        {"model": "auth.user"}
    ],
    
    # Configuración de navegación
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "votaciones"],
    
    # Iconos personalizados para el sistema electoral
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "votaciones": "fas fa-vote-yea",
        "votaciones.Votante": "fas fa-users",
        "votaciones.Candidato": "fas fa-user-tie",
        "votaciones.Plancha": "fas fa-list-ol",
        "votaciones.Voto": "fas fa-check-square",
        "votaciones.TipoConsejo": "fas fa-tags",
        "votaciones.EstadisticaVotacion": "fas fa-chart-bar"
    },
    
    # Enlaces personalizados por aplicación
    "custom_links": {
        "votaciones": [{
            "name": "Dashboard Electoral", 
            "url": "admin:dashboard", 
            "icon": "fas fa-chart-bar",
            "permissions": ["votaciones.view_voto"]
        }]
    },
    
    # Configuración de fuentes y UI
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    
    # Formato de formularios
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "votaciones.candidato": "vertical_tabs"
    },
    
    # Configuraciones adicionales
    "related_modal_active": True,
    "language_chooser": False,
}

# Configuración de colores y tema personalizado
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "#b71c1c",
    "accent": "#e31e24",
    "navbar": "#b71c1c",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "#f8f9fa",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True
}